### ISSUE TITLE
hazelcast 4.0 compatible version of hazelcast-zookeeper was not released

### ISSUE THREAD

**Issue by srikanth9488** [hazelcast/hazelcast-zookeeper#16]
Not able to use Zookeeper discovery strategy with Hazelcast 4.0 and Hazelcast-zookeeper 3.6.3. Throwing below exception:
The following method did not exist: com.hazelcast.spi.discovery.DiscoveryNode.getPrivateAddress()Lcom/hazelcast/nio/Address;

**Comment by mesutcelik** [comment]
Thanks @srikanth9488 , 
We are looking forward your contribution as discussed on gitter.  Initial work has already been done in [4.0-compatibility](https://github.com/hazelcast/hazelcast-zookeeper/tree/4.0-compatibility) branch.

**Comment by mesutcelik** [comment]
Hi @srikanth9488 
Have you had a chance to have a look at this issue in order to send a PR?

**Comment by srikanth9488** [comment]
Hi @mesutcelik, no. Since 4.0 was not compatible, we were forced to use 3.12.6 version in our organisation due to lack of time and resources during this covid-19 pandemic. So, didn't had a change to look at this issue again. Apologies for the same.

**Comment by pivovarit** [comment]
Hazelcast 4.0 support will be released in a few days in 4.0 release.

**Comment by pivovarit** [comment]
@srikanth9488 just to let you know - we just released the next version which is 4.0-compatible!

https://github.com/hazelcast/hazelcast-zookeeper/releases/tag/v4.0

**Comment by srikanth9488** [comment]
@pivovarit Thanks for the update. 👍
