### ISSUE TITLE
zookeeper discovery performance seems not good.

### ISSUE THREAD

**Issue by bwzhang2011** [hazelcast/hazelcast-zookeeper#2]
@kobalski, thanks a lot for bringing zookeeper integration support for zookeeper is widely used in our projects for service discovery. but when I tested with IQueue for loop testing, I found the performance dropped down compared with original configuration (the tcp configurable way). e.g  when use the tcp network configuration, the IQueue for each offer in my env will just cost near 1~2ms between machines, but under zookeeper discovery it will cost nearly 15ms which plays half of the statistic data.so I wonder why the performance dropped down so quickly for once it established the connection between client and server, the cost for zookeeper could  be ignored. so hope more performance testing could be provided. by the way, I built in with hazelcast3.6.1 branch code.

**Comment by bwzhang2011** [comment]
by the way here came the test log pic:
![image](https://cloud.githubusercontent.com/assets/749788/13277404/95bea9e6-db03-11e5-82ca-bcd0abc3cb6d.png)

the discovery test like this:
![image](https://cloud.githubusercontent.com/assets/749788/13277427/b3aa0248-db03-11e5-8bbc-03314f273e01.png)

**Comment by bwzhang2011** [comment]
@kobalski, please take a look at if you have your spare time and hope more performance tests compared could be provided.

**Comment by jerrinot** [comment]
@bwzhang2011: thanks for trying the new Zookeeper provider and your report!

The only explanation I have is that the Curator library used in the Zookeeper discovery module generates garbage and GC pauses effect your results. Could you please try the test with verbose GC log on on all your JVMs?

**Comment by bwzhang2011** [comment]
@jerrinot, thanks for your feed back and discovery module seems to be some very important feature since 3.6. as your comment, I don't quite understand your suggestion. for I only test it under very short time just some basic loop test and print each time cost and when switched to tcp join way, the time cost was near to the ping time but it dropped a lot when zookeeper brought in. compared to kafka which is also connecting to zookeeper, it was also very fast which seems that less impact due to the cost for curator or zookeeper client. by the way, the loop count could be very small just like 100 and then quit. so I dare say that curator was not the main reason and I suggested that more performance test should be brought in.

**Comment by bwzhang2011** [comment]
@jerrinot, would you mind leaving more message for your advice as I didn't quite understand that ?

**Comment by bwzhang2011** [comment]
@jerrinot, any update with such issue ?

**Comment by lazerion** [comment]
Hi @bwzhang2011,

Is performance problem still valid on your side?

**Comment by bwzhang2011** [comment]
I think I should close such issue now and reopen it once I encounter performance bottleneck afterwards. I'm sure that the discovery enabled some or else does impact the performance but it should be at most limited to a very low value.
