### ISSUE TITLE
Can't use existing curator instance

### ISSUE THREAD

**Issue by kofemann** [hazelcast/hazelcast-zookeeper#8]
Hi, 

In our code, we already using curator an, but hazelcast discovery creates an other one.  One of the solution I see is to pass existing instance through property map, something like:

```java
        CuratorFramework curator = ...;
        
        DiscoveryStrategyConfig discoveryStrategyConfig = new DiscoveryStrategyConfig(new ZookeeperDiscoveryStrategyFactory());
        discoveryStrategyConfig.addProperty(ZookeeperDiscoveryProperties.CURATOR_INSTANCE.key(), curator);
```
What do you think?

**Comment by lazerion** [comment]
Hi,

Your proposal can be done, however `CuratorFramework` client is a core attribute for Zookeeper discovery mechanism. Therefore, it is encapsulated by design and implementation, it is neither exposed nor can be injected.
